#!/bin/bash

OS_RELEASE_FILES="/usr/lib/os-release /etc/os-release"

function error() {
	echo "ERROR: $1" >&2
	exit $2
}

function warning() {
	echo "WARNING: $1" >&2
}

function check_os_release_file() {
	for file in $OS_RELEASE_FILES; do
		if [ -f "$file" ]; then
			return 0
		fi
	done
	echo "ERROR: No information (no such files: $OS_RELEASE_FILES)." 1>&2
	exit 1
}

function print_os_release_information() {
	IFS='='
	while read name value; do
		name=$(sed -e 's/\(.*\)/\L\1/g; s/_/\ /g; s/^./\U&/g; s/\ ./\U&/g' <<< $name)
		value=$(sed -e 's/"//g' <<< $value)
		printf "%16s: %s\n" $name $value
	done < $OS_RELEASE_FILE
}

function main() {
	check_os_release_file
	print_os_release_information
}

main "$@"

